pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO = '442122590814.dkr.ecr.us-east-1.amazonaws.com/user-service'
        IMAGE_NAME = 'user-service'
        GIT_REPO = 'https://github.com/abhin7821/microservices-devops-platform.git'
        GIT_CREDENTIALS = 'github-pat'             // Jenkins credential ID for GitHub PAT
        AWS_CREDENTIALS = 'jenkins-ecr-user'       // Jenkins credential ID for AWS
        ARGOCD_SERVER = 'argo-server-url'          // Optional: if you want to use CLI sync
    }

    stages {

        stage('Checkout') {
            steps {
                echo "📥 Checking out code from GitHub..."
                git branch: 'main',
                    credentialsId: "${GIT_CREDENTIALS}",
                    url: "${GIT_REPO}"
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "🐳 Building Docker image..."
                sh 'docker build -t $IMAGE_NAME:latest ./app'
            }
        }

        stage('Push to ECR') {
            steps {
                echo "🚀 Logging into ECR and pushing image..."
                withAWS(credentials: "${AWS_CREDENTIALS}", region: "${AWS_REGION}") {
                    sh '''
                        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
                        docker
